# Generated by Django 3.0.7 on 2020-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_price', models.CharField(blank=True, max_length=250)),
                ('cart_pizzas_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
