# Generated by Django 3.0.7 on 2020-06-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='cart_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='carts',
            old_name='cart_pizzas_id',
            new_name='pizzas_id',
        ),
        migrations.RenameField(
            model_name='carts',
            old_name='cart_price',
            new_name='price',
        ),
    ]
