# Generated by Django 3.0.7 on 2020-06-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('pizza_id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_name', models.CharField(max_length=250)),
            ],
        ),
    ]
