# Generated by Django 3.0.7 on 2020-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='pizza_category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='pizza_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='pizza_options',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='pizza_price',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
