# Generated by Django 3.0.7 on 2020-06-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20200608_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzas',
            old_name='pizza_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pizzas',
            old_name='pizza_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pizzas',
            old_name='pizza_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pizzas',
            old_name='pizza_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizzas',
            old_name='pizza_options',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='pizzas',
            old_name='pizza_price',
            new_name='price',
        ),
    ]
