# Generated by Django 3.0.7 on 2020-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20200610_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
