# Generated by Django 3.0.7 on 2020-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20200611_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
