# Generated by Django 3.0.7 on 2020-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.CharField(blank=True, max_length=250)),
                ('order_location', models.CharField(blank=True, max_length=250)),
                ('order_phone', models.CharField(blank=True, max_length=250)),
                ('order_addition_info', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
