# Generated by Django 3.0.7 on 2020-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_cart_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_person_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
