# Generated by Django 3.0.7 on 2020-06-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200610_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_addition_info',
            new_name='addition_info',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_cart_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_person_name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_price',
            new_name='price',
        ),
    ]
