# Generated by Django 3.0.7 on 2020-06-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200610_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='cart_id',
            new_name='pizza_list',
        ),
    ]
