# Generated by Django 3.0.7 on 2020-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200611_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pizza_list',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
