# Generated by Django 3.0.7 on 2020-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200611_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pizza_list',
            field=models.TextField(),
        ),
    ]
