# Generated by Django 3.0.7 on 2020-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200612_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
