# Generated by Django 3.0.7 on 2020-06-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_pizzas_image'),
        ('orders', '0008_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pizza_list',
        ),
        migrations.AddField(
            model_name='orders',
            name='pizza_list',
            field=models.ManyToManyField(to='pizzas.Pizzas'),
        ),
    ]
